### ISSUE TITLE
Page scrolls to 'top', when click on 'change page of result'

### ISSUE THREAD

**Issue by gesior** [sutara79/jquery.ajax-combobox#9]
When I click 'next'/'page number,' it scrolls page to top. It's because of:
<a href="#"
Plugin should use everywhere:
<a href="javascript:void(0)"
More information:
http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0

Tested in Google Chrome 45.

**Comment by guipedral** [comment]
In this case, the bind must be a "click" event, not "mouseup" on _ehNaviPaging method. I will take a new pull request to solve this issue.

**Comment by sutara79** [comment]
I will cope it at next patch update v7.4.5.
